apiVersion: v1
kind: ConfigMap
metadata:
  name: lotus-backend-config
  namespace: lotus-spm
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8085"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  JWT_EXPIRATION_MS: "86400000"
  CORS_ALLOWED_ORIGINS: "https://lotus-spm.com,https://www.lotus-spm.com"
